version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: html/scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: html/scripts/install_dependencies.sh
      timeout: 600
      runas: root
    - location: html/scripts/config_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: html/scripts/start_server.sh
      timeout: 300
      runas: root