version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html/
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/config_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root